from src.configs.models import RunConfig, Step, StepRevision, StepRevisionPool

llm = "groq/openai/gpt-oss-120b"

mini_config_big = RunConfig(
    final_follow_llm=llm,
    final_follow_times=10,
    max_concurrent_tasks=2,
    steps=[
        Step(
            instruction_llm=llm,
            follow_llm=llm,
            times=30,
            timeout_secs=300,
            include_base64=False,
            use_diffs=True,
        ),
        Step(
            instruction_llm=llm,
            follow_llm=llm,
            times=30,
            timeout_secs=300,
            include_base64=False,
            use_diffs=True,
        ),
        Step(
            instruction_llm=llm,
            follow_llm=llm,
            times=40,
            timeout_secs=300,
            include_base64=False,
            use_diffs=True,
        ),
        StepRevision(
            top_scores_used=10,
            instruction_llm=llm,
            follow_llm=llm,
            times_per_top_score=5,
            timeout_secs=300,
            include_base64=False,
            use_diffs=True,
        ),
        StepRevisionPool(
            top_scores_used=5,
            instruction_llm=llm,
            follow_llm=llm,
            times=10,
            timeout_secs=300,
            include_base64=False,
            use_diffs=True,
        ),
        StepRevision(
            top_scores_used=10,
            instruction_llm=llm,
            follow_llm=llm,
            times_per_top_score=5,
            timeout_secs=300,
            include_base64=False,
            use_diffs=True,
        ),
        StepRevisionPool(
            top_scores_used=5,
            instruction_llm=llm,
            follow_llm=llm,
            times=10,
            timeout_secs=300,
            include_base64=False,
            use_diffs=True,
        ),
    ],
)

mini_config = RunConfig(
    final_follow_llm=llm,
    final_follow_times=3,
    max_concurrent_tasks=2,
    steps=[
        Step(
            instruction_llm=llm,
            follow_llm=llm,
            times=3,
            timeout_secs=300,
            include_base64=False,
            use_diffs=True,
        ),
        StepRevision(
            top_scores_used=3,
            instruction_llm=llm,
            follow_llm=llm,
            times_per_top_score=1,
            timeout_secs=300,
            include_base64=False,
            use_diffs=True,
        ),
        StepRevisionPool(
            top_scores_used=3,
            instruction_llm=llm,
            follow_llm=llm,
            times=1,
            timeout_secs=300,
            include_base64=False,
            use_diffs=True,
        ),
    ],
)

mini_for_testing = RunConfig(
    final_follow_llm=llm,
    final_follow_times=2,
    max_concurrent_tasks=2,
    steps=[
        Step(
            instruction_llm=llm,
            follow_llm=llm,
            times=2,
            timeout_secs=300,
            include_base64=False,
            use_diffs=True,
        ),
        StepRevision(
            top_scores_used=2,
            instruction_llm=llm,
            follow_llm=llm,
            times_per_top_score=1,
            timeout_secs=300,
            include_base64=False,
            use_diffs=True,
        ),
        StepRevisionPool(
            top_scores_used=2,
            instruction_llm=llm,
            follow_llm=llm,
            times=1,
            timeout_secs=300,
            include_base64=False,
            use_diffs=True,
        ),
    ],
)
