from src.configs.models import RunConfig, Step, StepRevision, StepRevisionPool

llm = "openai/gpt-5.2"
gpt52_config_prod = RunConfig(
    final_follow_llm=llm,
    final_follow_times=3,
    max_concurrent_tasks=5,
    steps=[
        Step(
            instruction_llm=llm,
            follow_llm=llm,
            times=2,
            timeout_secs=10_800,
            include_base64=False,
            use_diffs=True,
        ),
        Step(
            instruction_llm=llm,
            follow_llm=llm,
            times=2,
            timeout_secs=10_800,
            include_base64=False,
            use_diffs=True,
        ),
        Step(
            instruction_llm=llm,
            follow_llm=llm,
            times=3,
            timeout_secs=10_800,
            include_base64=False,
            use_diffs=True,
        ),
        StepRevisionPool(
            top_scores_used=3,
            instruction_llm=llm,
            follow_llm=llm,
            times=2,
            timeout_secs=10_800,
            include_base64=False,
            use_diffs=True,
        ),
    ],
)

grok_config_old = RunConfig(
    final_follow_llm=llm,
    final_follow_times=5,
    max_concurrent_tasks=10,
    steps=[
        Step(
            instruction_llm=llm,
            follow_llm=llm,
            times=20,
            timeout_secs=10_800,
            include_base64=False,
            use_diffs=True,
        ),
        Step(
            instruction_llm=llm,
            follow_llm=llm,
            times=20,
            timeout_secs=10_800,
            include_base64=False,
            use_diffs=True,
        ),
        # Step(
        #     instruction_llm="openai/gpt-5.2",
        #     follow_llm="openai/gpt-5.2",
        #     times=20,
        #     timeout_secs=10_800,
        #     include_base64=False,
        #     use_diffs=True,
        # ),
        StepRevision(
            top_scores_used=5,
            instruction_llm=llm,
            follow_llm=llm,
            times_per_top_score=2,
            timeout_secs=10_800,
            include_base64=False,
            use_diffs=True,
        ),
        StepRevisionPool(
            top_scores_used=5,
            instruction_llm=llm,
            follow_llm=llm,
            times=10,
            timeout_secs=10_800,
            include_base64=False,
            use_diffs=True,
        ),
        # StepRevision(
        #     top_scores_used=5,
        #     instruction_llm=llm,
        #     follow_llm=llm,
        #     times_per_top_score=2,
        #     timeout_secs=10_800,
        #     include_base64=False,
        #     use_diffs=True,
        # ),
        # StepRevisionPool(
        #     top_scores_used=5,
        #     instruction_llm=llm,
        #     follow_llm=llm,
        #     times=5,
        #     timeout_secs=10_800,
        #     include_base64=False,
        #     use_diffs=True,
        # ),
    ],
)
